### ISSUE TITLE
2  tag in browse by language pointing to Page not found 

### ISSUE THREAD

**Issue by Priyanshu-official** [deepsourcelabs/good-first-issue#127]
Hi,
In browse by Language is 2 tag and one is blank (i.e [x3](https://goodfirstissue.dev/language/nil) &
[ Emacs Lisp x3](https://goodfirstissue.dev/language/emacs-lisp))

Pointing To the 404 page not Found.

![Screenshot from 2020-09-15 11-41-55](https://user-images.githubusercontent.com/55912091/93172856-46c1ca00-f749-11ea-8b19-fd37a3fe1446.jpg)

Any Suggestion if someone has I would Like to Work.

**Comment by sonuishaq67** [comment]
#53

**Comment by jai-deepsource** [comment]
@sonuishaq67 Thanks for the report. If you can send a fix via PR, would be more than happy to merge.

Or @rahul-deepsource , can you take a look?

**Comment by sonuishaq67** [comment]
I'll try this.

**Comment by ocean** [comment]
I've been having a look at this issue, and #97 and #53 which are all related, in my fork at https://github.com/ocean/good-first-issue

Sorry I should have commented when I started working on this a few days ago.
