### ISSUE TITLE
Import Error 

### ISSUE THREAD

**Issue by Priyanshu-official** [deepsourcelabs/good-first-issue#128]
Hi
there is error Coming in: 
good-first-issue/gfi/tweet.py
Line -18              => LOGGING_CONFIG 
Line-22,23,24     => Import error (Unable to Import toml)
![Screenshot from 2020-09-15 12-36-54](https://user-images.githubusercontent.com/55912091/93177566-a2438600-f750-11ea-9586-a72a684c20f6.jpg)

**Comment by sonuishaq67** [comment]
```pip3 install toml ``` ?

**Comment by Priyanshu-official** [comment]
@sonuishaq67  I have tried but not get Result.
you also try it and let me Know the result 
This is My first time.

**Comment by sonuishaq67** [comment]
works fine for me 
![Screenshot from 2020-09-20 16-12-36](https://user-images.githubusercontent.com/55189255/93709494-2b492b80-fb5c-11ea-94a2-517784dcf530.png)

**Comment by Priyanshu-official** [comment]
ok, Maybe Installation Problem form my side.
Thank you
