### ISSUE TITLE
Sort alphabetically data/repositories.toml to avoid conflicts

### ISSUE THREAD

**Issue by kmorcinek** [deepsourcelabs/good-first-issue#164]
Right now new repositories are added at the end of the list, and it causes git conflicts when couple PR are on the way. Requirement to have the list sorted will almost remove these conflicts.

**Comment by PRAy-d** [comment]
can i contribute on this?

**Comment by kmorcinek** [comment]
@PRAy-d you can help (if you can) by making PR #165 merged. What I did here is just sorted them in `vim` using `:sort`.
