### ISSUE TITLE
If an Emoji is in label project is not listed

### ISSUE THREAD

**Issue by darnuria** [deepsourcelabs/good-first-issue#170]
Project like [Peertube](https://github.com/Chocobozzz/PeerTube/) added an emojii in their label for beginners like "good first issue :beginner:"

Right now there is [some issues](https://github.com/Chocobozzz/PeerTube/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue+%3Abeginner%3A%22) labeled with this label but they don't appears on the goodFirstIssue listing. :(

I asked the same on Peertube folks side if just removing the emoji could help but maybe striping emoji at beginning/end of the label is not that bad.

**Comment by jSAMUELj** [comment]
@darnuria Hi can i work on this ?

**Comment by sanket-deepsource** [comment]
@darnuria We fetch the list of issues from the GitHub API with the label filter:

https://github.com/deepsourcelabs/good-first-issue/blob/406724faf8ae36da88abf59cdf74314119528e68/gfi/populate.py#L87-L93

So I'm not sure how we can support this in a generic way without explicitly whitelisting every variant (which isn't possible, of course). Do you have a solution in mind?

**Comment by darnuria** [comment]
I am not familiar with github API, but maybe a broad search with ignoring start and end before after `good first issue` might do the job.

Something like `🔰 good first issue` or good first issue 🔰` would match against

**Comment by sanket-deepsource** [comment]
Looks like the GitHub API supports searching/filtering of issues only via explicit labels ([docs](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-label)). I'm afraid we won't be able to support this feature until something changes on their end.

For the time being, maybe we can add some explicit known labels in `data/labels.json`. That is the only solution I can think of.
