### ISSUE TITLE
Show number of comments attached to the issue

### ISSUE THREAD

**Issue by timstarkk** [deepsourcelabs/good-first-issue#173]
I find the website very useful. Something that would increase the value of the website for me would be to see the number of comments attached to each issue. This would save me time in knowing which issues I'm interested in viewing. 

I would just add the feature and PR, but I have no idea how to get the project running locally.

If someone could help me get the project running locally, I could add the feature myself. 

Thanks.

**Comment by sanket-deepsource** [comment]
We're working on adding a guide for the local development setup in #187.

**Comment by pierreyoda** [comment]
Hi, just found this issue this morning and found it to be a very good idea. I tried to implement it the best I could.

FYI running the project locally is pretty simple, just follow the makefile and issue and/or export a Github API Personal Access Token.

**Comment by timstarkk** [comment]
@pierreyoda Thanks, I'll try that out. cheers.

**Comment by pierreyoda** [comment]
Just to say that this feature is merged and in production!

**Comment by harshit-deepsource** [comment]
closing this issue.
