### ISSUE TITLE
"good first issue" in README.md in darkmode not readable

### ISSUE THREAD

**Issue by eliastheis** [deepsourcelabs/good-first-issue#181]
### Here is a screenshot:
![darkmode_screenshot](https://user-images.githubusercontent.com/58971274/102382010-38927c80-3fca-11eb-99d2-ffc9e60c47d4.PNG)

### Maybe add a white background?

**Comment by ShyamPraveenSingh** [comment]
Hi, I would like to work on this issue.

**Comment by mohitdmak** [comment]
May I be assigned this issue?
