### ISSUE TITLE
Add a Guides section

### ISSUE THREAD

**Issue by sanket-deepsource** [deepsourcelabs/good-first-issue#189]
It will be valuable to write guides and how-tos around good first issues and open-source contributions. This can be implemented using Nuxt Content, and the guides can be written using Markdown.

**Comment by alokprince** [comment]
I am a beginner field of web development but I would like to work on this, please guide me.

**Comment by joeyouss** [comment]
@sanket-deepsource 
Hi! I would like to work on this issue and would write the relevant content pieces. Kindly assign the issue to me.
