### ISSUE TITLE
Guide: What is a good first issue?

### ISSUE THREAD

**Issue by sanket-deepsource** [deepsourcelabs/good-first-issue#192]
Outline:
* What is a good first issue?
* For project maintainers: how to create good first issues?
* For contributors: how to find an issue to get started?

The content should be live at: `/guide/what-is-good-first-issue`

**Comment by nilesh212** [comment]
Good first issues are the issues created by people on their projects. These issues are very easy to solve.

**Comment by sanket-deepsource** [comment]
@nilesh212 Would you be willing to contribute to the guide?

**Comment by nilesh212** [comment]
will you plz elaborate on it?

**Comment by aman190202** [comment]
@sanket-deepsource I would be willing to contribute to the guide!

**Comment by OmLakshmi** [comment]
@sanket-deepsource Would love to contribute to the guide

**Comment by Srijan0519** [comment]
@sanket-deepsource i would too

**Comment by Yashbontala** [comment]
would love to conrtribute

**Comment by kaitou-1412** [comment]
@sanket-deepsource A **good first issue** is an issue created for the sole purpose of facilitating newbies/beginners to jump-start their open journey.

**To get started**, one can use keywords related to what they already know, such as "python", or <any other programming language or topic> with keyword "issue" . 
#
Given below is an example of search terms used to find issue:

![Capture](https://user-images.githubusercontent.com/47006057/105052704-2fe40900-5a96-11eb-9d8e-8907a28a8485.JPG)

And lastly, I would like to contribute :)

**Comment by divyanshubisht** [comment]
can someone englighten me about all this. I am new to open source and looking forward towards this. So, if anyone could guide me. :)

**Comment by Chaitu17** [comment]
Can anyone please show me a good first issue, so that I can solve it. I'm a newbie to open source. Please help.

**Comment by Magicianred** [comment]
> Can anyone please show me a good first issue, so that I can solve it. I'm a newbie to open source. Please help.

Hi @Chaitu17 , you have to go in a Tracker Issue page and use this filter of search:
_is:issue is:open label:"good first issue"_ 

Read the description of issue, if you think to can resolve write some comment in the issue and ask to take in charge it, then resolve and create a PR to the repository :)
