### ISSUE TITLE
Add search for repos

### ISSUE THREAD

**Issue by sanketsaurav** [deepsourcelabs/good-first-issue#2]
Real-time search on owner, name, and language.

**Comment by developerfred** [comment]
Incredible here, I was going to suggest search algorithm <3 I was happy that there is already an open issue.

**Comment by jaipradeesh** [comment]
@developerfred Would you like to contribute? (or) should we keep it open?

**Comment by harshitsinghai77** [comment]
Is this issue still open?

**Comment by aleksandr-kotlyar** [comment]
> Is this issue still open?

Language filter is already on site. 

Search by "owner, name" - is "Ctrl+F" cause all repos are rendered at once on page open. May be in this case task can be closed.
