### ISSUE TITLE
Last activity data mismatch

### ISSUE THREAD

**Issue by urlDev** [deepsourcelabs/good-first-issue#215]
The last activity data on cards do not match with the ones in repos (last commit).

One repo I checked had the last commit from 17 months ago but on the website, it showed the last activity as 2 days.

**Comment by aleksandr-kotlyar** [comment]
I have a pull of questions in case to find out how to fix it. I want to discover how it should work and we make it better.

General questions are:
1. Where is the documented criteria of activity which good-first-issue should match or undertakes to fulfill?
2. What criteria should be used to sort projects?

Secondary questions to discuss:
1. Is 'last commit' the good criteria of activity?
2. @urlDev mean last commit to the master or to any other branch?
3. What about taking the activity from good-first-issue labeled issues? It can be a good point of maintaining too.

**Comment by urlDev** [comment]
Thank you for the answer. About your batch of questions;

General questions:
1. I have no information about what a good-first-issue should match for activity.
2. I believe sorting can be done in several ways e.g. last activity, number of issues, stars. What I first look at when checking for repos is the last activity because it gives an idea about how soon/fast your PR could be dealt with.

Secondary questions:
1. I believe 'last commit' would be good criteria, yes. 
2. Last commit to the master/main would be a good start.
3. I haven't thought of that. Thinking of it, the project might be really active but their good-first-issue labeled issues might not be new (e.g. react docs). So this wouldn't reflect the way when the last commit has been made. Can be two activity data (if not too complex to do); last activity (last commit), good-first-issue activity (when they were last labeled/merged)?

If I knew Vue, I would definitely work on this!

**Comment by aleksandr-kotlyar** [comment]
> If I knew Vue, I would definitely work on this!

@urlDev thank you for answers! Before programm something - we should now the requirements. I don't know vue either but i want to clear up what needs to be done in this issue, after that somebody could take it in progress, or we could practice with vue on the clarified algorithm.

**Comment by mukki00** [comment]
Hey guys! I know vue.js, so I think I can help you. But I don't have a clear idea of the issue. So, Can you please explain it further @urlDev ?

**Comment by aleksandr-kotlyar** [comment]
Relevant.
