### ISSUE TITLE
Search issues by having 'any one' label from data/labels.json

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [deepsourcelabs/good-first-issue#226]
From #54 by @RJ722 
> The way we query the GitHub API right now:
> 
> https://github.com/deepsourcelabs/good-first-issue/blob/82c11219150d60eefc33396201d5a8fea9b0fc41/gfi/populate.py#L79-L85
> 
> We do a logical AND for all the labels supplied from the `data/labels.json`. We'd need to change that to search for issues having any one, or more of the labels supplied.

I plan to fix it.

**Comment by aleksandr-kotlyar** [comment]
Waiting for review.

**Comment by RJ722** [comment]
Thanks for the PR! :)
