### ISSUE TITLE
bug: autofix for `Unnecessary parentheses after keyword` [Python] 

### ISSUE THREAD

**Issue by tusharnankani** [deepsourcelabs/good-first-issue#263]
In one of my repositories, I ran a [deepsource analysis](https://deepsource.io/gh/tusharnankani/url-shortener/) and in [one of the autofix sessions](https://deepsource.io/gh/tusharnankani/url-shortener/autofix/047f5269-75d7-4b87-bf8f-67d0c30f28dc/), it creates a buggy PR.

Style: Unnecessary parentheses after keyword `PYL-C0325`

![image](https://user-images.githubusercontent.com/61280281/118037321-50103e80-b38b-11eb-8b8e-8a70f1f3fc75.png)

```python
ifresult is None:
    print("This won't be printed, because NameError: name 'ifresult' is not defined")
```

**Comment by shubhendra-deepsource** [comment]
Hi @tusharnankani 👋 

This is the repository for [Goodfirstissue.dev](https://goodfirstissue.dev), and issues created here are related to that only.

I hope you won't mind using an option from below to report bugs.
- Post on [DeepSource's Discuss](https://discuss.deepsource.io/)
- Report on `#bugs` channel on [DeepSource's Users group](https://join.slack.com/t/deepsourceusers/shared_invite/zt-gfe1t4oi-DFaFfjLMXwxaz7iz3eLLzg) on Slack
- Chat button on DeepSource Dashboard
- Email support@deepsource.io

**Comment by tusharnankani** [comment]
Apologies @subham-deepsource! 
I tried to look for an accurate repository (under the deepsource organization) where I could address this issue, but couldn't find an appropriate one, so I reported the bug here. 

I will report the bug on one of the options you gave. 
Thank you for your help! ^_^
