### ISSUE TITLE
(JS-0712) Avoid `target='_blank'` attribute without `rel='noopener noreferrer'`

### ISSUE THREAD

**Issue by Praveen-jha** [deepsourcelabs/good-first-issue#283]
## Description
A malicious actor can gain full control over the user&#x27;s DOM window object. As such, this can lead to phishing attacks such as fake login prompts or password alerts being shown to the user. &lt;!--more--&gt; Using `target=&#x27;_blank&#x27;` links grants the page we are linking to a partial access to the …

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/deepsourcelabs/good-first-issue/issue/JS-0712/occurrences/](https://deepsource.io/gh/deepsourcelabs/good-first-issue/issue/JS-0712/occurrences/)

**Comment by dhruvMohapatra** [comment]
I'd like to fix this. Can I take a shot at it?

**Comment by AmanLakhani** [comment]
Can I help to fix this issue?
