### ISSUE TITLE
Can only owners add repos?

### ISSUE THREAD

**Issue by vasanthdharmaraj** [deepsourcelabs/good-first-issue#351]
I picked up a Kotlin good first issue in the [mockk](https://github.com/mockk/mockk) repo. 🎉 Thanks for providing this service.

But I noticed that there are only four repos for Kotlin. Another library I use has three `good first issue`: https://github.com/detekt/detekt/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

I was wondering if only repo owners can add new repos or others can add repos too?

**Comment by siddhant-deepsource** [comment]
Hey @vasanthdharmaraj 👋

Anyone can add repositories by creating a pull-request. You can find more details about adding repositories [here](https://github.com/deepsourcelabs/good-first-issue#adding-a-new-project).

Thanks!

**Comment by vasanthdharmaraj** [comment]
Great. Thanks.
