### ISSUE TITLE
Filter out the archived projects

### ISSUE THREAD

**Issue by btargac** [deepsourcelabs/good-first-issue#358]
Some projects are archived and there's no point of listing them anymore. I guess they have been added in the past and they were being actively maintained at the time they were added, but as of today when you list #javascript you get 105 results and the first one is Josh's [guppy](https://github.com/joshwcomeau/guppy) project which is already archived. So it would be better if they are filtered out in my opinion.

**Comment by tompitt94** [comment]
@btargac Can I take a run at this one please?

**Comment by btargac** [comment]
@tompitt94 I tried again, this time 103 results returned for JS and guppy was not the first one. I guess it was 10th or so but it was still in the list, and when I visited that repo it shows a notification "This repository has been archived by the owner. It is now read-only."

**Comment by tompitt94** [comment]
Thanks for getting back to me and letting me know.

I'll keep an eye on the other issues.

**Comment by jai-deepsource** [comment]
@siddhant-deepsource Can you take care of this?

**Comment by siddhant-deepsource** [comment]
@jai-deepsource Sure, will take this up.
