### ISSUE TITLE
Add filtering based on languages

### ISSUE THREAD

**Issue by jaipradeesh** [deepsourcelabs/good-first-issue#36]
A filter on the right or the left would be nice.

**Comment by RJ722** [comment]
This shall be handled as a part of #2. I'm planning to use [algolia] since we would already have a structured database already - the created JSON file.

**Comment by sanketsaurav** [comment]
@RJ722 Are you taking this up in this sprint? If not, I can take it up and add a temporary, permalink based fix for this.

**Comment by RJ722** [comment]
I don't have enough bandwidth this week.

> If not, I can take it up and add a temporary, permalink based fix for this.

That would be great, thank you!

I will take this from there onward.
