### ISSUE TITLE
(JS-0241) Consider using arrow functions for callbacks

### ISSUE THREAD

**Issue by meghrathod** [deepsourcelabs/good-first-issue#369]
## Description
It is recommended to use arrow functions as callbacks.

## Occurrences
There are 4 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/deepsourcelabs/good-first-issue/issue/JS-0241/occurrences/](https://deepsource.io/gh/deepsourcelabs/good-first-issue/issue/JS-0241/occurrences/)

**Comment by agarwalBinay18** [comment]
CAN you assign this to me?

**Comment by KingAzizz** [comment]
How can l take it and submit changes because I already fixed the issue

**Comment by sanjeevbhusal** [comment]
Hey is anyone assign to it?
