### ISSUE TITLE
Make your first contribution page

### ISSUE THREAD

**Issue by jaipradeesh** [deepsourcelabs/good-first-issue#38]
A page to guide new open-source contributors. This could include (but not limited to) commit best practices, pull request conventions, seeking help, picking a good first issue, code review etiquette, etc.

**Comment by fgiuliani** [comment]
@jaipradeesh what's the idea here?

**Comment by rajneesh44** [comment]
@RJ722 can you guide me what do we have to do here?

**Comment by jaipradeesh** [comment]
Hey @fgiuliani and @rajneesh44, I've updated the description with a bit more details. I think @kaustavdm is already working on it. I would wait for their comment. If it is still open, you're more than welcome to contribute.

**Comment by rajneesh44** [comment]
Ok Sure, Thanks @jaipradeesh.

**Comment by kaustavdm** [comment]
Hey @rajneesh44, here are the things we’d like to include in the page:

## Finding a repo

This section will talk about how to use the Good First Issue tool to find reps and issues to contribute to. 

## Setting up git

This section will give an introduction to git through links to other tutorials on the web, including GitHub’s and Atlassian’s docs.

## Sending your first pull request

This section will talk of the logistics of creating a patch and sending a PR to the chosen repo. Again, link to existing tutorials.

—-

The overall goal of this page is to be a list of resources for making the first contribution to a good first issue in any repo.

If you are up for taking it up, I recommend that you familiarise yourself with the source code in this repo, and create a draft PR with the new page. I’ll review and we can work together on pushing it to production.

In that sense, this issue itself is a good first issue. 😬

**Comment by IC1101Virgo** [comment]
Hey is this available? Anything that I can do or contribute?

**Comment by RJ722** [comment]
Hello @IC1101Virgo!

This project is still very early in development, and can use every bit of help available.

If you are willing to take this up, take a look at @kaustavdm's [comment](https://github.com/deepsourcelabs/good-first-issue/issues/38#issuecomment-630140112) on what we need to add.

Let me know if you have any questions, happy to help! Thanks!

**Comment by IC1101Virgo** [comment]
OK! Thanks for the reply!

**Comment by tiagostutz** [comment]
Hi there everybody! First of all I have to say how glad I'm to found this project with people helping open source beginners to get in. When you start this open source path, finding your "good first issue" is not an easy task. We had a

**Comment by shub-garg** [comment]
View my PR  please

**Comment by Sheetal777** [comment]
Hello. I have sent a pull request for README file update, if you could, please review the same.

**Comment by carlosdeque-s** [comment]
Hi I'm new at github and my experience with code is from the last 2 years with some months of innactivity in between.

Is there any task I could do or somethings I need to learn if I only have a small experience in Js, Ruby, Java, C++, Python?

Feel free to ask me from email if you have some suggestions or projects I could help you with - al386762@uji.es

**Comment by Maganpreet** [comment]
Hey can I start working on this?
