### ISSUE TITLE
Is there a way to run this locally?

### ISSUE THREAD

**Issue by vasanthdharmaraj** [deepsourcelabs/good-first-issue#393]
I would like to contribute by creating a PR to add variations of labels like `good-first-issue` and `:wave: Good First Issue` that I am seeing being used in some open source projects. There is also a related issue #278.

From what I understand, I just need to add the new labels to [labels.json](https://github.com/deepsourcelabs/good-first-issue/blob/master/data/labels.json) file. But wanted to check if there is a way to run the application locally to check.

I ran the following commands:
- `make pre-build`
- `make build`

but got the error:
` FATAL  Cannot find module './data/tags.json'`

**Comment by sanket-deepsource** [comment]
Hey @vasanthdharmaraj! The instructions for running the app locally have been updated in the README [here](https://github.com/deepsourcelabs/good-first-issue#setting-up-the-project-locally). Hope this helps!
