### ISSUE TITLE
Add label variations for good first issue

### ISSUE THREAD

**Issue by vasanthdharmaraj** [deepsourcelabs/good-first-issue#394]
I found some project that match the criteria to be added but have variations of the `good first issue` labels like `good-first-issue` and `:wave: Good First Issue` I would like to add these label variations and subsequently add these repos.

Example:
- https://github.com/JetBrains/Exposed/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue
- https://github.com/apollographql/apollo-kotlin/issues?q=is%3Aopen+is%3Aissue+label%3A%22%3Awave%3A+Good+First+Issue%22

I assume that adding these labels to [labels.json](https://github.com/deepsourcelabs/good-first-issue/blob/master/data/labels.json) would be sufficient.

**Comment by vasanthdharmaraj** [comment]
I will create a PR for this.

**Comment by jai-deepsource** [comment]
@vasanthdharmaraj This has been merged.
