### ISSUE TITLE
Build a twitter bot that tweets whenever a new repository is added

### ISSUE THREAD

**Issue by jaipradeesh** [deepsourcelabs/good-first-issue#4]
Twitter handle: @gfidev

**Comment by sam95** [comment]
Hi @jaipradeesh! 
How are we taking care of storing the repos that have already been tweeted? Will need to maintain some sort of a DB or any other type of persistent storage in order to avoid duplicate tweets. Let me know your thoughts so I can help by picking this up.

**Comment by jaipradeesh** [comment]
@sam95 Sure. The bot should tweet the repository only once (when it is added) -- to start with. And maybe down the line, we can figure out how to randomly tweet a repository every n days (without repeating).

**Comment by sam95** [comment]
@jaipradeesh how do we maintain persistent repository records in this case (storing whether we tweeted only once inspite of multiple deployments)? I was thinking we can try persistent redis instead of setting up a DB only for this case.

Let me know your thoughts.

**Comment by RJ722** [comment]
@sam95 maybe, listen to changes on [`data/repositories.toml`](https://github.com/deepsourcelabs/good-first-issue/blob/master/data/repositories.toml) on `master` branch.

Basically, push a tweet whenever a new line is added to the file.

We can safely assume that commits won't be rewritten (protected branch) and we already have checks in place to ensure that entries aren't duplicated.

**Comment by aneeshdua** [comment]
I am also looking into this. Cheers!

**Comment by aneeshdua** [comment]
I am planning to create and test the bot on my twitter account and then give you the docker image for your twitter handle. @jaipradeesh what do you say?

**Comment by jaipradeesh** [comment]
@sam95 That works. Apologies for the delay.

Also, can you help me understand the workflow?

**Comment by aneeshdua** [comment]
@jaipradeesh can i work on this?

**Comment by jaipradeesh** [comment]
Wow. This has been going on for a very long time now. @sam95 is working on it with @RJ722.

Let's wait for a couple more days. @aneeshdua Let me try to open up a few more issues in this repo.
