### ISSUE TITLE
Display repository description along with the name of the repo

### ISSUE THREAD

**Issue by jaipradeesh** [deepsourcelabs/good-first-issue#41]
<img width="760" alt="Screenshot 2020-04-30 at 9 07 17 PM" src="https://user-images.githubusercontent.com/4883668/80729977-9ac76b80-8b26-11ea-81d1-6b47a0b4c5d7.png">

**Comment by fgiuliani** [comment]
Can I work on this issue? @jaipradeesh

**Comment by jaipradeesh** [comment]
Appreciate it, @fgiuliani 

There is already an open PR - https://github.com/deepsourcelabs/good-first-issue/pull/42

**Comment by fgiuliani** [comment]
Didn't see the linked PR before. Sorry @jaipradeesh

**Comment by jaipradeesh** [comment]
I will try open a few more improvements over the course of the week :)
