### ISSUE TITLE
add search for issues by regex pattern, like `good.*first.*[issue/bug]`

### ISSUE THREAD

**Issue by anhtumai** [deepsourcelabs/good-first-issue#411]
Some repositories don't have the label `good-first-issue`, but they have labels `good-first-bug` or `good first issue`. Therefore, the list of good first issues on the web is lacking. For example, https://github.com/ogham/exa/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-bug. To query all possible results, we should query by regex pattern, like `good.*first.*[issue/bug]` instead of a hardcoded value: `good-first-issue`

**Comment by QuarkNerd** [comment]
`[]` will match a single character in the list. Something like `good.*first.*(issue)|(bug)|(ticket)` might work better?
Also I'd like to pick this up if allowed?

**Comment by QuarkNerd** [comment]
A cursory glance at the pygithub docs suggests that it doesnt like regexes for searching for issues, so maybe just  expanding the list is the way to go, it's not ideal but since people manually add their projects here, they should choose one of the ones mentioned here

**Comment by QuarkNerd** [comment]
We should close this issue, seems there is a duplicate https://github.com/deepsourcelabs/good-first-issue/issues/394

**Comment by anhtumai-spacehub** [comment]
agree
