### ISSUE TITLE
Emoji not rendered properly for some projects

### ISSUE THREAD

**Issue by jaipradeesh** [deepsourcelabs/good-first-issue#43]
<img width="746" alt="Screenshot 2020-05-07 at 1 18 21 PM" src="https://user-images.githubusercontent.com/4883668/81268216-4dd32000-9065-11ea-8529-4c5b2448dce9.png">

**Comment by fgiuliani** [comment]
GitHub is using <g-emoji> tags for these

<img width="1269" alt="Screen Shot 2020-05-12 at 01 02 34" src="https://user-images.githubusercontent.com/464646/81637260-4bb5ec00-93ec-11ea-887b-12f293b8fbec.png">

there's a package for Python that can be used to translate the emojis that are failing

https://pypi.org/project/emojis/

**Comment by fgiuliani** [comment]
PR open for this issue https://github.com/deepsourcelabs/good-first-issue/pull/51
