### ISSUE TITLE
Move labels to a separate file

### ISSUE THREAD

**Issue by jaipradeesh** [deepsourcelabs/good-first-issue#44]
Move labels to `labels.json` file under `data` directory.

This would enable us to add more beginner issue tags like `easy-pickings`, `E-easy`, etc.

**Comment by jaipradeesh** [comment]
@fgiuliani Interested to take this one up?

**Comment by fgiuliani** [comment]
@jaipradeesh sure!

**Comment by fgiuliani** [comment]
PR created https://github.com/deepsourcelabs/good-first-issue/pull/46

**Comment by jaipradeesh** [comment]
Thanks for the contribution @fgiuliani

**Comment by fgiuliani** [comment]
I think this issue can be closed @jaipradeesh
