### ISSUE TITLE
adding code of conduct file

### ISSUE THREAD

**Issue by anamikarawat** [deepsourcelabs/good-first-issue#473]
I want to create a code_of_conduct.md file . please assign me this issue under hacktoberfest 2022.

**Comment by Siddharthqr** [comment]
Assign me this issue

**Comment by Mani628** [comment]
assign me this issue

**Comment by ayushmaanshrotriya** [comment]
I can do it

**Comment by Poeticjustice98** [comment]
> I can do it

Me too?
