### ISSUE TITLE
Archived repositories in the results

### ISSUE THREAD

**Issue by ankit-verma-209171** [deepsourcelabs/good-first-issue#527]
While exploring the website for active repositories to contribute to, I found [sveltejs/sapper](https://github.com/sveltejs/sapper) repo which is archived. Although, it still contain good first issues, we can't contribute as it is read only 😅

**Comment by tushar-deepsource** [comment]
@ankit-verma-209171 thanks for the report! I'll try to get this fixed as soon as possible.

**Comment by tushar-deepsource** [comment]
It should be live within 10 minutes.
