### ISSUE TITLE
When filtering by "C#" the results displayed are for "C"

### ISSUE THREAD

**Issue by fgiuliani** [deepsourcelabs/good-first-issue#53]
If I filter repositories selecting "C#" language, the results displayed are for "C" language (the url that I'm redirected to is https://goodfirstissue.dev/language/c)

**Comment by kaustavdm** [comment]
Thanks for reporting this, @fgiuliani. Confirmed that I can reproduce it. Let’s see if anyone can take it up soon.

**Comment by fgiuliani** [comment]
@kaustavdm I can work on this

**Comment by kaustavdm** [comment]
Excellent! Let me know if you need any help. This project is still in its early days, and contribution is very much welcome. 😊

**Comment by fgiuliani** [comment]
I'm taking my first steps with pythong/hugo and this got more complicated than I thought.
I think the issue is here, but I'm not finding a way to encode the URL

https://github.com/deepsourcelabs/good-first-issue/blob/master/themes/lucy/layouts/_default/baseof.html#L19

Looks like we need to generate this URL
https://goodfirstissue.dev/language/c%23

I spent some time trying to make it work but I was not able to do it.

I also detected that there are issues with other two languages

<img width="332" alt="Screen Shot 2020-05-18 at 17 06 32" src="https://user-images.githubusercontent.com/464646/82254822-f6b53100-9929-11ea-9d2b-79ef15ca577b.png">

"Emacs Lisp" is redirecting to a 404, and there's an empty tag (nil language?)

**Comment by sidntrivedi012** [comment]
Hey @fgiuliani,

I guess `urlize` is removing the `#`. Adding to that, we need to encode it to `%23`. In order to do that, I guess we can use `replace`(https://gohugo.io/functions/replace/) function of Hugo to replace `#` in `$url` with `%23`. 

Adding to that, there is a comment here which may help - https://discourse.gohugo.io/t/url-encoding-percent-encoding-with-hugo-solved/16546/10.

I am not fully sure though but we can try it.

**Comment by fgiuliani** [comment]
thanks for the response @sidntrivedi012 !

The replace is a good approach. My concern is what happens If in the future more cases of languages with "special characters" appear. Adding a replace for each character maybe gets messy. The replace is a good temporary solution, though.

On the other hand, I'm not too familiar with Hugo, but do you know how can we fix the other two issues? (the empty language and the "Emacs Lisp" 404 redirect).

Thank you for your comment!

**Comment by mayank-genesis** [comment]
Hey, @fgiuliani also there is an issue with "/jupyter-note"  as well. Here we clearly conclude that links containing special-chars are not working.

**Comment by ocean** [comment]
I've sort of fixed the C# issue in PR #162, but not fully happy with it.

**Comment by sanket-deepsource** [comment]
This has been fixed in #183.
