### ISSUE TITLE
Get issues from other beginner-friendly labels

### ISSUE THREAD

**Issue by jaipradeesh** [deepsourcelabs/good-first-issue#54]
For ex: `easy pickings`, `E-easy`, etc.

To be added to file: https://github.com/deepsourcelabs/good-first-issue/blob/master/data/labels.json

**Comment by RJ722** [comment]
The way we query the GitHub API right now:

https://github.com/deepsourcelabs/good-first-issue/blob/82c11219150d60eefc33396201d5a8fea9b0fc41/gfi/populate.py#L79-L85

We do a logical AND for all the labels supplied from the `data/labels.json`. We'd need to change that to search for issues having any one, or more of the labels supplied. Until then, let's keep this issue on hold.

**Comment by Sheldon-Lloyd** [comment]
Interesting idea but I wonder how one would determine what issues are easy. What is easy for one person might be harder for someone else.

**Comment by carlosdeque-s** [comment]
Hi I'm new at github and my experience with code is from the last 2 years with some months of innactivity in between.

Is there any task I could do or somethings I need to learn if I only have a small experience in Js, Ruby, Java, C++, Python?

Feel free to ask me from email if you have some suggestions or projects I could help you with - al386762@uji.es

**Comment by aleksandr-kotlyar** [comment]
> The way we query the GitHub API right now:
> 
> https://github.com/deepsourcelabs/good-first-issue/blob/82c11219150d60eefc33396201d5a8fea9b0fc41/gfi/populate.py#L79-L85
> 
> We do a logical AND for all the labels supplied from the `data/labels.json`. We'd need to change that to search for issues having any one, or more of the labels supplied. Until then, let's keep this issue on hold.

Fixed in #227 that was the "good first issue" too, easy to make.  🙂

**Comment by rahul-deepsource** [comment]
Thanks to @aleksandr-kotlyar, the search would be an `ANY` type search, wherein issue will be reported if it matches any of the given labels. This issue is no longer blocked.
