### ISSUE TITLE
Website isn't updated when new repos are added

### ISSUE THREAD

**Issue by etr2460** [deepsourcelabs/good-first-issue#71]
I added Apache Superset a couple weeks ago, but don't see it reflected in the goodfirstissue.dev website. Is there something else needed to to be done to deploy the website?

**Comment by sanketsaurav** [comment]
Thanks for the report, @etr2460. This was caused due to a bug in the repository generation script, that was breaking the deployment build. I've pushed a fix for this in #74, and the repositories you had added should reflect on the next deployment (that happens every 30 mins.)
