### ISSUE TITLE
Missing swift tag in language container

### ISSUE THREAD

**Issue by maayami** [deepsourcelabs/good-first-issue#88]
There is no tag for swift. Moreover, links with special-chars are not working!

_Originally posted by @mayank-genesis in https://github.com/deepsourcelabs/good-first-issue/issues/53#issuecomment-664793834_

**Comment by Ask-Subhasmita** [comment]
@maayami hey I would like to work on this issue, can you guide me how can I reproduce the issue?

**Comment by carlosdeque-s** [comment]
Hi I'm new at github and my experience with code is from the last 2 years with some months of innactivity in between.

Is there any task I could do or somethings I need to learn if I only have a small experience in Js, Ruby, Java, C++, Python?

Feel free to ask me from email if you have some suggestions or projects I could help you with - al386762@uji.es

**Comment by sanket-deepsource** [comment]
This has been handled in the latest release. Thanks for reporting!
